# Generated by Django 5.0.4 on 2026-08-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_topology'),
        ('projects', '0002_alter_customer_id_alter_measurementitem_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementitem',
            name='topology',
            field=models.ForeignKey(blank=True, help_text='Panel configuration selected for this opening', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_items', to='catalog.topology'),
        ),
    ]
