# Generated by Django 5.0.4 on 2026-08-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_fix_formula_position_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code, unique within the system, e.g. 2S, 1F1S', max_length=20)),
                ('name', models.CharField(help_text="e.g. '2 Sliding', '1 Fixed + 1 Openable'", max_length=150)),
                ('shape', models.CharField(choices=[('rectangle', 'Rectangle'), ('semi_circle_top', 'Semicircle Top'), ('arch_top', 'Arched Top')], default='rectangle', max_length=20)),
                ('panel_layout', models.JSONField(default=list, help_text='Ordered list of panel type tokens, e.g. ["sliding", "sliding"]. Drives both the preview thumbnail and the default panel count.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topologies', to='catalog.system')),
            ],
            options={
                'ordering': ['system', 'sort_order', 'code'],
                'unique_together': {('system', 'code')},
            },
        ),
    ]
